name: bombando
description: Bombando Em Portugal

publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  html: ^0.15.1
  just_audio: ^0.9.30
  toast: ^0.3.0
  folder_file_saver: ^2.0.4
  permission_handler: ^10.2.0
  dio: ^4.0.6
  path_provider: ^2.0.11
  ringtone_set: ^0.0.3
  icons_launcher: ^2.0.5
  flutter_native_splash: ^2.2.12
  flutter_staggered_grid_view: ^0.6.2
  awesome_dialog: ^3.0.2
  adaptive_theme: ^3.1.1
  icony: ^1.0.5
  settings_ui: ^2.0.2
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:

    - assets/images/

#Launcher Icons
icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    windows:
      enable: true
    linux:
      enable: true

#Splash Screen
flutter_native_splash:

  color: "#ffffff"

  android_12:
 
    branding: assets/images/logo.png