name: bombando
description: Bombando Em Portugal

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  double_back_to_close_app: ^2.1.0
  http: ^0.13.5
  html: ^0.15.1
  just_audio: ^0.9.30
  toast: ^0.3.0
  folder_file_saver: ^2.0.4
  permission_handler: ^10.2.0
  dio: ^4.0.6
  path_provider: ^2.0.11
  ringtone_set: ^0.0.3
  icons_launcher: ^2.0.5
  flutter_native_splash: ^2.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

#Launcher Icons
icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    windows:
      enable: true
    linux:
      enable: true

#Splash Screen
flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#ffffff"

  android_12:
 
    branding: assets/images/logo.png